dog_shelters/urls.py
from django.urls import path
from . import views

app_name = 'dog_shelters'

urlpatterns = [
    path('classes/<int:pk>', views.index, name='index'),
    path('', views.classe_list, name='classe_list'),
    path('classe/<int:pk>', views.classe_detail, name='classe_detail'),
    # path('classes/<int:pk>', views.classe_delete, name='classe_delete')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
 path('', include('dog_shelters.urls')),
 path('admin/', admin.site.urls),
]

dog_shelters/models.py
from django.db import models


class Classe(models.Model):
 nom = models.CharField(max_length=200)
 specialite = models.CharField(max_length=200)
 def __str__(self):
    return self.nom

class Etudiant(models.Model):
 classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
 nom = models.CharField(max_length=200)
 prenom = models.TextField()
 dateNaiss = models.DateTimeField(auto_now_add=True)
 def __str__(self):
    return self.nom

dog_shelters/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from . import models

# Create your views here.
def index(request, pk):
    context = {'pk': pk}
    if request.method == 'POST':
        nom = request.POST.get('a')
        prenom = request.POST.get('b')
        dateNaiss = request.POST.get('c')
        d = request.POST.get('d')
        classe = get_object_or_404(models.Classe, pk=d)
        user = models.Etudiant.objects.create(nom=nom, prenom=prenom, dateNaiss=dateNaiss, classe=classe)
    return render(request, 'templates/index.html', context=context)

def classe_list(request):
    classes = models.Classe.objects.all()
    context = { 'classes': classes }
    return render(request, 'templates/classe_list.html', context=context)


def et_list(request):
    etudiants = models.Etudiant.objects.all()
    context = { 'etudiants': etudiants }
    return render(request, 'templates/classe_list.html', context=context)


def classe_detail(request, pk):
    classe = get_object_or_404(models.Classe, pk=pk)
    etudiant = models.Etudiant.objects.filter(classe = classe)
    context = {'classe': classe, 'etudiants': etudiant}
    return render(request, 'templates/classe_detail.html', context=context)

dog_shelters/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <title>{% block title %}Etudiant classe site{% endblock %}</title>

</head>
<body>
    <header class="header">
        <h1>Etudiants</h1>
    </header>
 <article class="container">
 <section class="jumbotron">
 </section>
 {% block content %}
 {% endblock %}
 </article>
</body>
</html>

dog_shelters/templates/classe_detail.html
{% extends 'base.html' %}
{% block title %}
Etudiants
{% endblock %}
{% block content %}
<div class="list">

    <div class="contener">
        <div class="link_back">
            <a href="{% url 'dog_shelters:classe_list' %}">
                <- Liste des étudiants </a>
                
        </div>
        <h1>{{ classe.nom }}</h1>
        <div class="contener">
            <h3>Spécialité: {{ classe.specialite }}</h3>
        </div>
        <a href="{% url 'dog_shelters:index' classe.id %}">
            Ajouter des étudiants </a>
        <div>
            <h1>Les etudiants disponibles </h1>
        </div>
        <table>
            <thead>
                <tr>
                    <td>Nom</td>
                    <td>Prenom</td>
                    <td>Date de naissance</td>
                </tr>
            </thead>
            <tbody>
                {% for etudiant in etudiants %}
                <tr>
                    <td>
                        {{etudiant.nom}}
                    </td>
                    <td>{{etudiant.prenom}}</td>
                    <td>{{etudiant.dateNaiss}}</td>
                    <!-- <td>Suprimer / modifier</td> -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
 
</div>
{% endblock %}

dog_shelters/templates/classe_list.html
{% extends 'base.html' %}
{% block title %}
Nos Etudiants
{% endblock %}
{% block content %}
<div class="list">
    <h1>Liste des Classes </h1>
    <table>
        <thead>
            <tr>
                <td>Nom</td>
                <td>Specialite</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            {% for classe in classes %}
            <tr>
                <td> 
                        {{classe.nom}}
                </td>
                <td>{{classe.specialite }}</td>
                <td><a href="{% url 'dog_shelters:classe_detail' classe.id %}">
                    Voir la liste des étudiants
                </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
<!-- hunterjul007@gmail.com -->
{% endblock %}

dog_shelters/templates/index.html
{% extends 'base.html' %}
{% block title %}
Etudiant
{% endblock %}
{% block content %}
<div class="container">
    <a href="{% url 'dog_shelters:classe_detail' pk %}">
        Retour </a>
    <form style=" margin: auto; width: 500px; margin-top: 50px; border: 1px springgreen solid; padding: 10px;"  method="post">
        {% csrf_token %}
        <h1>Ajouter un Etudiant</h1>
            <div>
                <label for="a">Nom</label>
                <input style="width: 100%;" type="text" name="a" id="a">
            </div>
            <div>
                <label for="b">Prenom</label>
                <input  style="width: 100%;" type="text" name="b" id="b">
            </div>
            <div>
                <label for="b">Date Naissance</label>
                <input style="width: 100%;" type="date" name="c" id="c">
            </div>
            <div>
                
                <input style="width: 100%; opacity: 0;" value="{{ pk }}" type="text" name="d" id="d">
            </div>
        <button style="margin-top: 10px;" type="submit">Ajouter</button>
    </form>
</div>
{% endblock %}